### ISSUE TITLE
Questions on further developments.

### ISSUE THREAD

**Issue by ghost** [dominicbarnes/node-siren-writer#2]
Hi Dominic!

Thanks for writing node-siren-writer. Yesterday I was running into your major rewrite, while reinstalling my node modules. I fixed this for me by creating a fork of your repository and creating a branch 0.0.1 myself.

As you can imagine I have some questions concerning further development now. ;)

First of all what was the reason for this hard break in developments. Any critical issues with 0.0.1? Second question would be, how do imagine further development of this library? Will there be a 0.0.1 compatible api in future?

Thanks for all. Best regards,
Dennis

**Comment by dominicbarnes** [comment]
Hey there! Thanks for taking the time to submit this issue.

The main issue I had with the fluent API before was that it got really difficult to keep code clean. This applied internally, as there was weird hacks going on to preserve context while switching between the entity, sub-entities, links, etc. Usually, internal complexity is acceptable if it makes the consuming code easier to write, which I just did not find to be the case in practice.

The other main problem was the use of positional arguments, I could _never_ remember what order things went in! (and I'm the one who wrote the library!) Not only that, but it makes it really hard to understand code just at a glance. (especially after not looking at it for a few days)

In general, I'm moving away from fluent APIs, as I find options objects to be far more flexible and readable. I will not be making any further changes that are compatible with the old `0.0.1` release.
