### ISSUE TITLE
Rels with dashes do not work

### ISSUE THREAD

**Issue by alex-murashkin** [dominicbarnes/node-siren-writer#3]
"prev-archive" and "next-archive" are in the IANA spec. However, the siren writer can't resolve rels with dashes and prepends the full URL to them on rendering, e.g.:
`links:[
...
 { "rel": [ "my-site-name/prev-archive" ], "href": "..." }
]`

A fix for that would be adding a reference to "to-camel-case", and, at line 44, add a call to it: `if (camel(rel) in iana)...`

**Comment by dominicbarnes** [comment]
Haha, wow that's a pretty silly bug I have. I'll be fixing that tonight.
