### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by solsend2l** [dominicbarnes/node-siren-writer#5]
Hi - it would be helpful to add these props to your `package.json`:
- repository
- bugs.url
- homepage

**Comment by dominicbarnes** [comment]
Haha, you are totally right. I'll do that now

**Comment by dominicbarnes** [comment]
v0.2.1 has added `repository` and `bugs` (no `homepage` though, since there isn't really one aside from the github repo)

**Comment by solsend2l** [comment]
:+1:
